// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package sorinpo.scr.edu.model;

import org.springframework.beans.factory.annotation.Configurable;
import sorinpo.scr.edu.model.Pupil;

privileged aspect Pupil_Roo_Configurable {
    
    declare @type: Pupil: @Configurable;
    
}
