// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package sorinpo.scr.edu;

import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Configurable;
import org.springframework.test.context.ActiveProfiles;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.test.context.web.WebAppConfiguration;

privileged aspect CommonTestAnnotations {
    
	declare @type: sorinpo.scr.edu..*IntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
	declare @type: sorinpo.scr.edu..*IntegrationTest: @Configurable;
    declare @type: sorinpo.scr.edu..*IntegrationTest: @WebAppConfiguration;
    declare @type: sorinpo.scr.edu..*IntegrationTest: @ActiveProfiles("test");
    
}
