// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package sorinpo.scr.edu.model;

import java.util.List;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;
import sorinpo.scr.edu.model.CentruInfo;
import sorinpo.scr.edu.model.CentruInfoDataOnDemand;
import sorinpo.scr.edu.model.CentruInfoIntegrationTest;

privileged aspect CentruInfoIntegrationTest_Roo_IntegrationTest {
    
    declare @type: CentruInfoIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: CentruInfoIntegrationTest: @Transactional;
    
    @Autowired
    CentruInfoDataOnDemand CentruInfoIntegrationTest.dod;
    
    @Test
    public void CentruInfoIntegrationTest.testCountCentruInfoes() {
        Assert.assertNotNull("Data on demand for 'CentruInfo' failed to initialize correctly", dod.getRandomCentruInfo());
        long count = CentruInfo.countCentruInfoes();
        Assert.assertTrue("Counter for 'CentruInfo' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void CentruInfoIntegrationTest.testFindCentruInfo() {
        CentruInfo obj = dod.getRandomCentruInfo();
        Assert.assertNotNull("Data on demand for 'CentruInfo' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'CentruInfo' failed to provide an identifier", id);
        obj = CentruInfo.findCentruInfo(id);
        Assert.assertNotNull("Find method for 'CentruInfo' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'CentruInfo' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void CentruInfoIntegrationTest.testFindAllCentruInfoes() {
        Assert.assertNotNull("Data on demand for 'CentruInfo' failed to initialize correctly", dod.getRandomCentruInfo());
        long count = CentruInfo.countCentruInfoes();
        Assert.assertTrue("Too expensive to perform a find all test for 'CentruInfo', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<CentruInfo> result = CentruInfo.findAllCentruInfoes();
        Assert.assertNotNull("Find all method for 'CentruInfo' illegally returned null", result);
        Assert.assertTrue("Find all method for 'CentruInfo' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void CentruInfoIntegrationTest.testFindCentruInfoEntries() {
        Assert.assertNotNull("Data on demand for 'CentruInfo' failed to initialize correctly", dod.getRandomCentruInfo());
        long count = CentruInfo.countCentruInfoes();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<CentruInfo> result = CentruInfo.findCentruInfoEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'CentruInfo' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'CentruInfo' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void CentruInfoIntegrationTest.testFlush() {
        CentruInfo obj = dod.getRandomCentruInfo();
        Assert.assertNotNull("Data on demand for 'CentruInfo' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'CentruInfo' failed to provide an identifier", id);
        obj = CentruInfo.findCentruInfo(id);
        Assert.assertNotNull("Find method for 'CentruInfo' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyCentruInfo(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'CentruInfo' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void CentruInfoIntegrationTest.testMergeUpdate() {
        CentruInfo obj = dod.getRandomCentruInfo();
        Assert.assertNotNull("Data on demand for 'CentruInfo' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'CentruInfo' failed to provide an identifier", id);
        obj = CentruInfo.findCentruInfo(id);
        boolean modified =  dod.modifyCentruInfo(obj);
        Integer currentVersion = obj.getVersion();
        CentruInfo merged = obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'CentruInfo' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void CentruInfoIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'CentruInfo' failed to initialize correctly", dod.getRandomCentruInfo());
        CentruInfo obj = dod.getNewTransientCentruInfo(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'CentruInfo' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'CentruInfo' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        Assert.assertNotNull("Expected 'CentruInfo' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void CentruInfoIntegrationTest.testRemove() {
        CentruInfo obj = dod.getRandomCentruInfo();
        Assert.assertNotNull("Data on demand for 'CentruInfo' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'CentruInfo' failed to provide an identifier", id);
        obj = CentruInfo.findCentruInfo(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'CentruInfo' with identifier '" + id + "'", CentruInfo.findCentruInfo(id));
    }
    
}
