// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package sorinpo.scr.edu.model;

import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.stereotype.Component;
import sorinpo.scr.edu.model.Info;
import sorinpo.scr.edu.model.InfoDataOnDemand;
import sorinpo.scr.edu.model.MonthlyNumbers;

privileged aspect InfoDataOnDemand_Roo_DataOnDemand {
    
    declare @type: InfoDataOnDemand: @Component;
    
    private Random InfoDataOnDemand.rnd = new SecureRandom();
    
    private List<Info> InfoDataOnDemand.data;
    
    public Info InfoDataOnDemand.getNewTransientInfo(int index) {
        Info obj = new Info();
        setBeneficiariIndirecti(obj, index);
        setVoluntariImplicati(obj, index);
        setIntalniriGrupuriLucru(obj, index);
        setParticipantiGrupuriLucru(obj, index);
        setConferinteOrganizate(obj, index);
        setParticipantiConferinte(obj, index);
        setAparitiiPresa(obj, index);
        setLinks(obj, index);
        setUserId(obj, index);
        setYear(obj, index);
        return obj;
    }
    
    public void InfoDataOnDemand.setBeneficiariIndirecti(Info obj, int index) {
        MonthlyNumbers embeddedClass = new MonthlyNumbers();
        setBeneficiariIndirectiJan(embeddedClass, index);
        setBeneficiariIndirectiFeb(embeddedClass, index);
        setBeneficiariIndirectiMar(embeddedClass, index);
        setBeneficiariIndirectiApr(embeddedClass, index);
        setBeneficiariIndirectiMay(embeddedClass, index);
        setBeneficiariIndirectiJun(embeddedClass, index);
        setBeneficiariIndirectiJul(embeddedClass, index);
        setBeneficiariIndirectiAug(embeddedClass, index);
        setBeneficiariIndirectiSep(embeddedClass, index);
        setBeneficiariIndirectiOct(embeddedClass, index);
        setBeneficiariIndirectiNov(embeddedClass, index);
        setBeneficiariIndirectiDec(embeddedClass, index);
        obj.setBeneficiariIndirecti(embeddedClass);
    }
    
    public void InfoDataOnDemand.setBeneficiariIndirectiJan(MonthlyNumbers obj, int index) {
        int jan = index;
        obj.setJan(jan);
    }
    
    public void InfoDataOnDemand.setBeneficiariIndirectiFeb(MonthlyNumbers obj, int index) {
        int feb = index;
        obj.setFeb(feb);
    }
    
    public void InfoDataOnDemand.setBeneficiariIndirectiMar(MonthlyNumbers obj, int index) {
        int mar = index;
        obj.setMar(mar);
    }
    
    public void InfoDataOnDemand.setBeneficiariIndirectiApr(MonthlyNumbers obj, int index) {
        int apr = index;
        obj.setApr(apr);
    }
    
    public void InfoDataOnDemand.setBeneficiariIndirectiMay(MonthlyNumbers obj, int index) {
        int may = index;
        obj.setMay(may);
    }
    
    public void InfoDataOnDemand.setBeneficiariIndirectiJun(MonthlyNumbers obj, int index) {
        int jun = index;
        obj.setJun(jun);
    }
    
    public void InfoDataOnDemand.setBeneficiariIndirectiJul(MonthlyNumbers obj, int index) {
        int jul = index;
        obj.setJul(jul);
    }
    
    public void InfoDataOnDemand.setBeneficiariIndirectiAug(MonthlyNumbers obj, int index) {
        int aug = index;
        obj.setAug(aug);
    }
    
    public void InfoDataOnDemand.setBeneficiariIndirectiSep(MonthlyNumbers obj, int index) {
        int sep = index;
        obj.setSep(sep);
    }
    
    public void InfoDataOnDemand.setBeneficiariIndirectiOct(MonthlyNumbers obj, int index) {
        int oct = index;
        obj.setOct(oct);
    }
    
    public void InfoDataOnDemand.setBeneficiariIndirectiNov(MonthlyNumbers obj, int index) {
        int nov = index;
        obj.setNov(nov);
    }
    
    public void InfoDataOnDemand.setBeneficiariIndirectiDec(MonthlyNumbers obj, int index) {
        int dec = index;
        obj.setDec(dec);
    }
    
    public void InfoDataOnDemand.setVoluntariImplicati(Info obj, int index) {
        MonthlyNumbers embeddedClass = new MonthlyNumbers();
        setVoluntariImplicatiJan(embeddedClass, index);
        setVoluntariImplicatiFeb(embeddedClass, index);
        setVoluntariImplicatiMar(embeddedClass, index);
        setVoluntariImplicatiApr(embeddedClass, index);
        setVoluntariImplicatiMay(embeddedClass, index);
        setVoluntariImplicatiJun(embeddedClass, index);
        setVoluntariImplicatiJul(embeddedClass, index);
        setVoluntariImplicatiAug(embeddedClass, index);
        setVoluntariImplicatiSep(embeddedClass, index);
        setVoluntariImplicatiOct(embeddedClass, index);
        setVoluntariImplicatiNov(embeddedClass, index);
        setVoluntariImplicatiDec(embeddedClass, index);
        obj.setVoluntariImplicati(embeddedClass);
    }
    
    public void InfoDataOnDemand.setVoluntariImplicatiJan(MonthlyNumbers obj, int index) {
        int jan = index;
        obj.setJan(jan);
    }
    
    public void InfoDataOnDemand.setVoluntariImplicatiFeb(MonthlyNumbers obj, int index) {
        int feb = index;
        obj.setFeb(feb);
    }
    
    public void InfoDataOnDemand.setVoluntariImplicatiMar(MonthlyNumbers obj, int index) {
        int mar = index;
        obj.setMar(mar);
    }
    
    public void InfoDataOnDemand.setVoluntariImplicatiApr(MonthlyNumbers obj, int index) {
        int apr = index;
        obj.setApr(apr);
    }
    
    public void InfoDataOnDemand.setVoluntariImplicatiMay(MonthlyNumbers obj, int index) {
        int may = index;
        obj.setMay(may);
    }
    
    public void InfoDataOnDemand.setVoluntariImplicatiJun(MonthlyNumbers obj, int index) {
        int jun = index;
        obj.setJun(jun);
    }
    
    public void InfoDataOnDemand.setVoluntariImplicatiJul(MonthlyNumbers obj, int index) {
        int jul = index;
        obj.setJul(jul);
    }
    
    public void InfoDataOnDemand.setVoluntariImplicatiAug(MonthlyNumbers obj, int index) {
        int aug = index;
        obj.setAug(aug);
    }
    
    public void InfoDataOnDemand.setVoluntariImplicatiSep(MonthlyNumbers obj, int index) {
        int sep = index;
        obj.setSep(sep);
    }
    
    public void InfoDataOnDemand.setVoluntariImplicatiOct(MonthlyNumbers obj, int index) {
        int oct = index;
        obj.setOct(oct);
    }
    
    public void InfoDataOnDemand.setVoluntariImplicatiNov(MonthlyNumbers obj, int index) {
        int nov = index;
        obj.setNov(nov);
    }
    
    public void InfoDataOnDemand.setVoluntariImplicatiDec(MonthlyNumbers obj, int index) {
        int dec = index;
        obj.setDec(dec);
    }
    
    public void InfoDataOnDemand.setIntalniriGrupuriLucru(Info obj, int index) {
        MonthlyNumbers embeddedClass = new MonthlyNumbers();
        setIntalniriGrupuriLucruJan(embeddedClass, index);
        setIntalniriGrupuriLucruFeb(embeddedClass, index);
        setIntalniriGrupuriLucruMar(embeddedClass, index);
        setIntalniriGrupuriLucruApr(embeddedClass, index);
        setIntalniriGrupuriLucruMay(embeddedClass, index);
        setIntalniriGrupuriLucruJun(embeddedClass, index);
        setIntalniriGrupuriLucruJul(embeddedClass, index);
        setIntalniriGrupuriLucruAug(embeddedClass, index);
        setIntalniriGrupuriLucruSep(embeddedClass, index);
        setIntalniriGrupuriLucruOct(embeddedClass, index);
        setIntalniriGrupuriLucruNov(embeddedClass, index);
        setIntalniriGrupuriLucruDec(embeddedClass, index);
        obj.setIntalniriGrupuriLucru(embeddedClass);
    }
    
    public void InfoDataOnDemand.setIntalniriGrupuriLucruJan(MonthlyNumbers obj, int index) {
        int jan = index;
        obj.setJan(jan);
    }
    
    public void InfoDataOnDemand.setIntalniriGrupuriLucruFeb(MonthlyNumbers obj, int index) {
        int feb = index;
        obj.setFeb(feb);
    }
    
    public void InfoDataOnDemand.setIntalniriGrupuriLucruMar(MonthlyNumbers obj, int index) {
        int mar = index;
        obj.setMar(mar);
    }
    
    public void InfoDataOnDemand.setIntalniriGrupuriLucruApr(MonthlyNumbers obj, int index) {
        int apr = index;
        obj.setApr(apr);
    }
    
    public void InfoDataOnDemand.setIntalniriGrupuriLucruMay(MonthlyNumbers obj, int index) {
        int may = index;
        obj.setMay(may);
    }
    
    public void InfoDataOnDemand.setIntalniriGrupuriLucruJun(MonthlyNumbers obj, int index) {
        int jun = index;
        obj.setJun(jun);
    }
    
    public void InfoDataOnDemand.setIntalniriGrupuriLucruJul(MonthlyNumbers obj, int index) {
        int jul = index;
        obj.setJul(jul);
    }
    
    public void InfoDataOnDemand.setIntalniriGrupuriLucruAug(MonthlyNumbers obj, int index) {
        int aug = index;
        obj.setAug(aug);
    }
    
    public void InfoDataOnDemand.setIntalniriGrupuriLucruSep(MonthlyNumbers obj, int index) {
        int sep = index;
        obj.setSep(sep);
    }
    
    public void InfoDataOnDemand.setIntalniriGrupuriLucruOct(MonthlyNumbers obj, int index) {
        int oct = index;
        obj.setOct(oct);
    }
    
    public void InfoDataOnDemand.setIntalniriGrupuriLucruNov(MonthlyNumbers obj, int index) {
        int nov = index;
        obj.setNov(nov);
    }
    
    public void InfoDataOnDemand.setIntalniriGrupuriLucruDec(MonthlyNumbers obj, int index) {
        int dec = index;
        obj.setDec(dec);
    }
    
    public void InfoDataOnDemand.setParticipantiGrupuriLucru(Info obj, int index) {
        MonthlyNumbers embeddedClass = new MonthlyNumbers();
        setParticipantiGrupuriLucruJan(embeddedClass, index);
        setParticipantiGrupuriLucruFeb(embeddedClass, index);
        setParticipantiGrupuriLucruMar(embeddedClass, index);
        setParticipantiGrupuriLucruApr(embeddedClass, index);
        setParticipantiGrupuriLucruMay(embeddedClass, index);
        setParticipantiGrupuriLucruJun(embeddedClass, index);
        setParticipantiGrupuriLucruJul(embeddedClass, index);
        setParticipantiGrupuriLucruAug(embeddedClass, index);
        setParticipantiGrupuriLucruSep(embeddedClass, index);
        setParticipantiGrupuriLucruOct(embeddedClass, index);
        setParticipantiGrupuriLucruNov(embeddedClass, index);
        setParticipantiGrupuriLucruDec(embeddedClass, index);
        obj.setParticipantiGrupuriLucru(embeddedClass);
    }
    
    public void InfoDataOnDemand.setParticipantiGrupuriLucruJan(MonthlyNumbers obj, int index) {
        int jan = index;
        obj.setJan(jan);
    }
    
    public void InfoDataOnDemand.setParticipantiGrupuriLucruFeb(MonthlyNumbers obj, int index) {
        int feb = index;
        obj.setFeb(feb);
    }
    
    public void InfoDataOnDemand.setParticipantiGrupuriLucruMar(MonthlyNumbers obj, int index) {
        int mar = index;
        obj.setMar(mar);
    }
    
    public void InfoDataOnDemand.setParticipantiGrupuriLucruApr(MonthlyNumbers obj, int index) {
        int apr = index;
        obj.setApr(apr);
    }
    
    public void InfoDataOnDemand.setParticipantiGrupuriLucruMay(MonthlyNumbers obj, int index) {
        int may = index;
        obj.setMay(may);
    }
    
    public void InfoDataOnDemand.setParticipantiGrupuriLucruJun(MonthlyNumbers obj, int index) {
        int jun = index;
        obj.setJun(jun);
    }
    
    public void InfoDataOnDemand.setParticipantiGrupuriLucruJul(MonthlyNumbers obj, int index) {
        int jul = index;
        obj.setJul(jul);
    }
    
    public void InfoDataOnDemand.setParticipantiGrupuriLucruAug(MonthlyNumbers obj, int index) {
        int aug = index;
        obj.setAug(aug);
    }
    
    public void InfoDataOnDemand.setParticipantiGrupuriLucruSep(MonthlyNumbers obj, int index) {
        int sep = index;
        obj.setSep(sep);
    }
    
    public void InfoDataOnDemand.setParticipantiGrupuriLucruOct(MonthlyNumbers obj, int index) {
        int oct = index;
        obj.setOct(oct);
    }
    
    public void InfoDataOnDemand.setParticipantiGrupuriLucruNov(MonthlyNumbers obj, int index) {
        int nov = index;
        obj.setNov(nov);
    }
    
    public void InfoDataOnDemand.setParticipantiGrupuriLucruDec(MonthlyNumbers obj, int index) {
        int dec = index;
        obj.setDec(dec);
    }
    
    public void InfoDataOnDemand.setConferinteOrganizate(Info obj, int index) {
        MonthlyNumbers embeddedClass = new MonthlyNumbers();
        setConferinteOrganizateJan(embeddedClass, index);
        setConferinteOrganizateFeb(embeddedClass, index);
        setConferinteOrganizateMar(embeddedClass, index);
        setConferinteOrganizateApr(embeddedClass, index);
        setConferinteOrganizateMay(embeddedClass, index);
        setConferinteOrganizateJun(embeddedClass, index);
        setConferinteOrganizateJul(embeddedClass, index);
        setConferinteOrganizateAug(embeddedClass, index);
        setConferinteOrganizateSep(embeddedClass, index);
        setConferinteOrganizateOct(embeddedClass, index);
        setConferinteOrganizateNov(embeddedClass, index);
        setConferinteOrganizateDec(embeddedClass, index);
        obj.setConferinteOrganizate(embeddedClass);
    }
    
    public void InfoDataOnDemand.setConferinteOrganizateJan(MonthlyNumbers obj, int index) {
        int jan = index;
        obj.setJan(jan);
    }
    
    public void InfoDataOnDemand.setConferinteOrganizateFeb(MonthlyNumbers obj, int index) {
        int feb = index;
        obj.setFeb(feb);
    }
    
    public void InfoDataOnDemand.setConferinteOrganizateMar(MonthlyNumbers obj, int index) {
        int mar = index;
        obj.setMar(mar);
    }
    
    public void InfoDataOnDemand.setConferinteOrganizateApr(MonthlyNumbers obj, int index) {
        int apr = index;
        obj.setApr(apr);
    }
    
    public void InfoDataOnDemand.setConferinteOrganizateMay(MonthlyNumbers obj, int index) {
        int may = index;
        obj.setMay(may);
    }
    
    public void InfoDataOnDemand.setConferinteOrganizateJun(MonthlyNumbers obj, int index) {
        int jun = index;
        obj.setJun(jun);
    }
    
    public void InfoDataOnDemand.setConferinteOrganizateJul(MonthlyNumbers obj, int index) {
        int jul = index;
        obj.setJul(jul);
    }
    
    public void InfoDataOnDemand.setConferinteOrganizateAug(MonthlyNumbers obj, int index) {
        int aug = index;
        obj.setAug(aug);
    }
    
    public void InfoDataOnDemand.setConferinteOrganizateSep(MonthlyNumbers obj, int index) {
        int sep = index;
        obj.setSep(sep);
    }
    
    public void InfoDataOnDemand.setConferinteOrganizateOct(MonthlyNumbers obj, int index) {
        int oct = index;
        obj.setOct(oct);
    }
    
    public void InfoDataOnDemand.setConferinteOrganizateNov(MonthlyNumbers obj, int index) {
        int nov = index;
        obj.setNov(nov);
    }
    
    public void InfoDataOnDemand.setConferinteOrganizateDec(MonthlyNumbers obj, int index) {
        int dec = index;
        obj.setDec(dec);
    }
    
    public void InfoDataOnDemand.setParticipantiConferinte(Info obj, int index) {
        MonthlyNumbers embeddedClass = new MonthlyNumbers();
        setParticipantiConferinteJan(embeddedClass, index);
        setParticipantiConferinteFeb(embeddedClass, index);
        setParticipantiConferinteMar(embeddedClass, index);
        setParticipantiConferinteApr(embeddedClass, index);
        setParticipantiConferinteMay(embeddedClass, index);
        setParticipantiConferinteJun(embeddedClass, index);
        setParticipantiConferinteJul(embeddedClass, index);
        setParticipantiConferinteAug(embeddedClass, index);
        setParticipantiConferinteSep(embeddedClass, index);
        setParticipantiConferinteOct(embeddedClass, index);
        setParticipantiConferinteNov(embeddedClass, index);
        setParticipantiConferinteDec(embeddedClass, index);
        obj.setParticipantiConferinte(embeddedClass);
    }
    
    public void InfoDataOnDemand.setParticipantiConferinteJan(MonthlyNumbers obj, int index) {
        int jan = index;
        obj.setJan(jan);
    }
    
    public void InfoDataOnDemand.setParticipantiConferinteFeb(MonthlyNumbers obj, int index) {
        int feb = index;
        obj.setFeb(feb);
    }
    
    public void InfoDataOnDemand.setParticipantiConferinteMar(MonthlyNumbers obj, int index) {
        int mar = index;
        obj.setMar(mar);
    }
    
    public void InfoDataOnDemand.setParticipantiConferinteApr(MonthlyNumbers obj, int index) {
        int apr = index;
        obj.setApr(apr);
    }
    
    public void InfoDataOnDemand.setParticipantiConferinteMay(MonthlyNumbers obj, int index) {
        int may = index;
        obj.setMay(may);
    }
    
    public void InfoDataOnDemand.setParticipantiConferinteJun(MonthlyNumbers obj, int index) {
        int jun = index;
        obj.setJun(jun);
    }
    
    public void InfoDataOnDemand.setParticipantiConferinteJul(MonthlyNumbers obj, int index) {
        int jul = index;
        obj.setJul(jul);
    }
    
    public void InfoDataOnDemand.setParticipantiConferinteAug(MonthlyNumbers obj, int index) {
        int aug = index;
        obj.setAug(aug);
    }
    
    public void InfoDataOnDemand.setParticipantiConferinteSep(MonthlyNumbers obj, int index) {
        int sep = index;
        obj.setSep(sep);
    }
    
    public void InfoDataOnDemand.setParticipantiConferinteOct(MonthlyNumbers obj, int index) {
        int oct = index;
        obj.setOct(oct);
    }
    
    public void InfoDataOnDemand.setParticipantiConferinteNov(MonthlyNumbers obj, int index) {
        int nov = index;
        obj.setNov(nov);
    }
    
    public void InfoDataOnDemand.setParticipantiConferinteDec(MonthlyNumbers obj, int index) {
        int dec = index;
        obj.setDec(dec);
    }
    
    public void InfoDataOnDemand.setAparitiiPresa(Info obj, int index) {
        MonthlyNumbers embeddedClass = new MonthlyNumbers();
        setAparitiiPresaJan(embeddedClass, index);
        setAparitiiPresaFeb(embeddedClass, index);
        setAparitiiPresaMar(embeddedClass, index);
        setAparitiiPresaApr(embeddedClass, index);
        setAparitiiPresaMay(embeddedClass, index);
        setAparitiiPresaJun(embeddedClass, index);
        setAparitiiPresaJul(embeddedClass, index);
        setAparitiiPresaAug(embeddedClass, index);
        setAparitiiPresaSep(embeddedClass, index);
        setAparitiiPresaOct(embeddedClass, index);
        setAparitiiPresaNov(embeddedClass, index);
        setAparitiiPresaDec(embeddedClass, index);
        obj.setAparitiiPresa(embeddedClass);
    }
    
    public void InfoDataOnDemand.setAparitiiPresaJan(MonthlyNumbers obj, int index) {
        int jan = index;
        obj.setJan(jan);
    }
    
    public void InfoDataOnDemand.setAparitiiPresaFeb(MonthlyNumbers obj, int index) {
        int feb = index;
        obj.setFeb(feb);
    }
    
    public void InfoDataOnDemand.setAparitiiPresaMar(MonthlyNumbers obj, int index) {
        int mar = index;
        obj.setMar(mar);
    }
    
    public void InfoDataOnDemand.setAparitiiPresaApr(MonthlyNumbers obj, int index) {
        int apr = index;
        obj.setApr(apr);
    }
    
    public void InfoDataOnDemand.setAparitiiPresaMay(MonthlyNumbers obj, int index) {
        int may = index;
        obj.setMay(may);
    }
    
    public void InfoDataOnDemand.setAparitiiPresaJun(MonthlyNumbers obj, int index) {
        int jun = index;
        obj.setJun(jun);
    }
    
    public void InfoDataOnDemand.setAparitiiPresaJul(MonthlyNumbers obj, int index) {
        int jul = index;
        obj.setJul(jul);
    }
    
    public void InfoDataOnDemand.setAparitiiPresaAug(MonthlyNumbers obj, int index) {
        int aug = index;
        obj.setAug(aug);
    }
    
    public void InfoDataOnDemand.setAparitiiPresaSep(MonthlyNumbers obj, int index) {
        int sep = index;
        obj.setSep(sep);
    }
    
    public void InfoDataOnDemand.setAparitiiPresaOct(MonthlyNumbers obj, int index) {
        int oct = index;
        obj.setOct(oct);
    }
    
    public void InfoDataOnDemand.setAparitiiPresaNov(MonthlyNumbers obj, int index) {
        int nov = index;
        obj.setNov(nov);
    }
    
    public void InfoDataOnDemand.setAparitiiPresaDec(MonthlyNumbers obj, int index) {
        int dec = index;
        obj.setDec(dec);
    }
    
    public void InfoDataOnDemand.setLinks(Info obj, int index) {
        String links = "links_" + index;
        obj.setLinks(links);
    }
    
    public void InfoDataOnDemand.setUserId(Info obj, int index) {
        Long userId = new Integer(index).longValue();
        obj.setUserId(userId);
    }
    
    public void InfoDataOnDemand.setYear(Info obj, int index) {
        int year = index;
        obj.setYear(year);
    }
    
    public Info InfoDataOnDemand.getSpecificInfo(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        Info obj = data.get(index);
        Long id = obj.getId();
        return Info.findInfo(id);
    }
    
    public Info InfoDataOnDemand.getRandomInfo() {
        init();
        Info obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return Info.findInfo(id);
    }
    
    public boolean InfoDataOnDemand.modifyInfo(Info obj) {
        return false;
    }
    
    public void InfoDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = Info.findInfoEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'Info' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<Info>();
        for (int i = 0; i < 10; i++) {
            Info obj = getNewTransientInfo(i);
            try {
                obj.persist();
            } catch (ConstraintViolationException e) {
                StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getConstraintDescriptor()).append(":").append(cv.getMessage()).append("=").append(cv.getInvalidValue()).append("]");
                }
                throw new RuntimeException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
