// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package sorinpo.scr.edu.model;

import java.util.Iterator;
import java.util.List;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;
import sorinpo.scr.edu.model.Participation;
import sorinpo.scr.edu.model.ParticipationDataOnDemand;
import sorinpo.scr.edu.model.ParticipationIntegrationTest;

privileged aspect ParticipationIntegrationTest_Roo_IntegrationTest {
    
    declare @type: ParticipationIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: ParticipationIntegrationTest: @Transactional;
    
    @Autowired
    ParticipationDataOnDemand ParticipationIntegrationTest.dod;
    
    @Test
    public void ParticipationIntegrationTest.testCountParticipations() {
        Assert.assertNotNull("Data on demand for 'Participation' failed to initialize correctly", dod.getRandomParticipation());
        long count = Participation.countParticipations();
        Assert.assertTrue("Counter for 'Participation' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void ParticipationIntegrationTest.testFindParticipation() {
        Participation obj = dod.getRandomParticipation();
        Assert.assertNotNull("Data on demand for 'Participation' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Participation' failed to provide an identifier", id);
        obj = Participation.findParticipation(id);
        Assert.assertNotNull("Find method for 'Participation' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'Participation' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void ParticipationIntegrationTest.testFindAllParticipations() {
        Assert.assertNotNull("Data on demand for 'Participation' failed to initialize correctly", dod.getRandomParticipation());
        long count = Participation.countParticipations();
        Assert.assertTrue("Too expensive to perform a find all test for 'Participation', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<Participation> result = Participation.findAllParticipations();
        Assert.assertNotNull("Find all method for 'Participation' illegally returned null", result);
        Assert.assertTrue("Find all method for 'Participation' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void ParticipationIntegrationTest.testFindParticipationEntries() {
        Assert.assertNotNull("Data on demand for 'Participation' failed to initialize correctly", dod.getRandomParticipation());
        long count = Participation.countParticipations();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<Participation> result = Participation.findParticipationEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'Participation' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'Participation' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void ParticipationIntegrationTest.testFlush() {
        Participation obj = dod.getRandomParticipation();
        Assert.assertNotNull("Data on demand for 'Participation' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Participation' failed to provide an identifier", id);
        obj = Participation.findParticipation(id);
        Assert.assertNotNull("Find method for 'Participation' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyParticipation(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'Participation' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void ParticipationIntegrationTest.testMergeUpdate() {
        Participation obj = dod.getRandomParticipation();
        Assert.assertNotNull("Data on demand for 'Participation' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Participation' failed to provide an identifier", id);
        obj = Participation.findParticipation(id);
        boolean modified =  dod.modifyParticipation(obj);
        Integer currentVersion = obj.getVersion();
        Participation merged = obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'Participation' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void ParticipationIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'Participation' failed to initialize correctly", dod.getRandomParticipation());
        Participation obj = dod.getNewTransientParticipation(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'Participation' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'Participation' identifier to be null", obj.getId());
        try {
            obj.persist();
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        obj.flush();
        Assert.assertNotNull("Expected 'Participation' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void ParticipationIntegrationTest.testRemove() {
        Participation obj = dod.getRandomParticipation();
        Assert.assertNotNull("Data on demand for 'Participation' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Participation' failed to provide an identifier", id);
        obj = Participation.findParticipation(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'Participation' with identifier '" + id + "'", Participation.findParticipation(id));
    }
    
}
