// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package sorinpo.scr.edu.model;

import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.stereotype.Component;
import sorinpo.scr.edu.model.ActivityData;
import sorinpo.scr.edu.model.ParentalCommunicationData;
import sorinpo.scr.edu.model.Participation;
import sorinpo.scr.edu.model.ParticipationDataOnDemand;
import sorinpo.scr.edu.model.Pupil.ParentState;

privileged aspect ParticipationDataOnDemand_Roo_DataOnDemand {
    
    declare @type: ParticipationDataOnDemand: @Component;
    
    private Random ParticipationDataOnDemand.rnd = new SecureRandom();
    
    private List<Participation> ParticipationDataOnDemand.data;
    
    public Participation ParticipationDataOnDemand.getNewTransientParticipation(int index) {
        Participation obj = new Participation();
        setSchool(obj, index);
        setFreeTime(obj, index);
        setExtraSchool(obj, index);
        setGroupCounseling(obj, index);
        setIndividualCounseling(obj, index);
        setParentalCommunication(obj, index);
        setLocalMeetings(obj, index);
        setParentalCommunicationDetailed(obj, index);
        setPupilId(obj, index);
        setYear(obj, index);
        return obj;
    }
    
    public void ParticipationDataOnDemand.setSchool(Participation obj, int index) {
        ActivityData embeddedClass = new ActivityData();
        setSchoolJan(embeddedClass, index);
        setSchoolFeb(embeddedClass, index);
        setSchoolMar(embeddedClass, index);
        setSchoolApr(embeddedClass, index);
        setSchoolMay(embeddedClass, index);
        setSchoolJun(embeddedClass, index);
        setSchoolJul(embeddedClass, index);
        setSchoolAug(embeddedClass, index);
        setSchoolSep(embeddedClass, index);
        setSchoolOct(embeddedClass, index);
        setSchoolNov(embeddedClass, index);
        setSchoolDec(embeddedClass, index);
        obj.setSchool(embeddedClass);
    }
    
    public void ParticipationDataOnDemand.setSchoolJan(ActivityData obj, int index) {
        Boolean jan = Boolean.TRUE;
        obj.setJan(jan);
    }
    
    public void ParticipationDataOnDemand.setSchoolFeb(ActivityData obj, int index) {
        Boolean feb = Boolean.TRUE;
        obj.setFeb(feb);
    }
    
    public void ParticipationDataOnDemand.setSchoolMar(ActivityData obj, int index) {
        Boolean mar = Boolean.TRUE;
        obj.setMar(mar);
    }
    
    public void ParticipationDataOnDemand.setSchoolApr(ActivityData obj, int index) {
        Boolean apr = Boolean.TRUE;
        obj.setApr(apr);
    }
    
    public void ParticipationDataOnDemand.setSchoolMay(ActivityData obj, int index) {
        Boolean may = Boolean.TRUE;
        obj.setMay(may);
    }
    
    public void ParticipationDataOnDemand.setSchoolJun(ActivityData obj, int index) {
        Boolean jun = Boolean.TRUE;
        obj.setJun(jun);
    }
    
    public void ParticipationDataOnDemand.setSchoolJul(ActivityData obj, int index) {
        Boolean jul = Boolean.TRUE;
        obj.setJul(jul);
    }
    
    public void ParticipationDataOnDemand.setSchoolAug(ActivityData obj, int index) {
        Boolean aug = Boolean.TRUE;
        obj.setAug(aug);
    }
    
    public void ParticipationDataOnDemand.setSchoolSep(ActivityData obj, int index) {
        Boolean sep = Boolean.TRUE;
        obj.setSep(sep);
    }
    
    public void ParticipationDataOnDemand.setSchoolOct(ActivityData obj, int index) {
        Boolean oct = Boolean.TRUE;
        obj.setOct(oct);
    }
    
    public void ParticipationDataOnDemand.setSchoolNov(ActivityData obj, int index) {
        Boolean nov = Boolean.TRUE;
        obj.setNov(nov);
    }
    
    public void ParticipationDataOnDemand.setSchoolDec(ActivityData obj, int index) {
        Boolean dec = Boolean.TRUE;
        obj.setDec(dec);
    }
    
    public void ParticipationDataOnDemand.setFreeTime(Participation obj, int index) {
        ActivityData embeddedClass = new ActivityData();
        setFreeTimeJan(embeddedClass, index);
        setFreeTimeFeb(embeddedClass, index);
        setFreeTimeMar(embeddedClass, index);
        setFreeTimeApr(embeddedClass, index);
        setFreeTimeMay(embeddedClass, index);
        setFreeTimeJun(embeddedClass, index);
        setFreeTimeJul(embeddedClass, index);
        setFreeTimeAug(embeddedClass, index);
        setFreeTimeSep(embeddedClass, index);
        setFreeTimeOct(embeddedClass, index);
        setFreeTimeNov(embeddedClass, index);
        setFreeTimeDec(embeddedClass, index);
        obj.setFreeTime(embeddedClass);
    }
    
    public void ParticipationDataOnDemand.setFreeTimeJan(ActivityData obj, int index) {
        Boolean jan = Boolean.TRUE;
        obj.setJan(jan);
    }
    
    public void ParticipationDataOnDemand.setFreeTimeFeb(ActivityData obj, int index) {
        Boolean feb = Boolean.TRUE;
        obj.setFeb(feb);
    }
    
    public void ParticipationDataOnDemand.setFreeTimeMar(ActivityData obj, int index) {
        Boolean mar = Boolean.TRUE;
        obj.setMar(mar);
    }
    
    public void ParticipationDataOnDemand.setFreeTimeApr(ActivityData obj, int index) {
        Boolean apr = Boolean.TRUE;
        obj.setApr(apr);
    }
    
    public void ParticipationDataOnDemand.setFreeTimeMay(ActivityData obj, int index) {
        Boolean may = Boolean.TRUE;
        obj.setMay(may);
    }
    
    public void ParticipationDataOnDemand.setFreeTimeJun(ActivityData obj, int index) {
        Boolean jun = Boolean.TRUE;
        obj.setJun(jun);
    }
    
    public void ParticipationDataOnDemand.setFreeTimeJul(ActivityData obj, int index) {
        Boolean jul = Boolean.TRUE;
        obj.setJul(jul);
    }
    
    public void ParticipationDataOnDemand.setFreeTimeAug(ActivityData obj, int index) {
        Boolean aug = Boolean.TRUE;
        obj.setAug(aug);
    }
    
    public void ParticipationDataOnDemand.setFreeTimeSep(ActivityData obj, int index) {
        Boolean sep = Boolean.TRUE;
        obj.setSep(sep);
    }
    
    public void ParticipationDataOnDemand.setFreeTimeOct(ActivityData obj, int index) {
        Boolean oct = Boolean.TRUE;
        obj.setOct(oct);
    }
    
    public void ParticipationDataOnDemand.setFreeTimeNov(ActivityData obj, int index) {
        Boolean nov = Boolean.TRUE;
        obj.setNov(nov);
    }
    
    public void ParticipationDataOnDemand.setFreeTimeDec(ActivityData obj, int index) {
        Boolean dec = Boolean.TRUE;
        obj.setDec(dec);
    }
    
    public void ParticipationDataOnDemand.setExtraSchool(Participation obj, int index) {
        ActivityData embeddedClass = new ActivityData();
        setExtraSchoolJan(embeddedClass, index);
        setExtraSchoolFeb(embeddedClass, index);
        setExtraSchoolMar(embeddedClass, index);
        setExtraSchoolApr(embeddedClass, index);
        setExtraSchoolMay(embeddedClass, index);
        setExtraSchoolJun(embeddedClass, index);
        setExtraSchoolJul(embeddedClass, index);
        setExtraSchoolAug(embeddedClass, index);
        setExtraSchoolSep(embeddedClass, index);
        setExtraSchoolOct(embeddedClass, index);
        setExtraSchoolNov(embeddedClass, index);
        setExtraSchoolDec(embeddedClass, index);
        obj.setExtraSchool(embeddedClass);
    }
    
    public void ParticipationDataOnDemand.setExtraSchoolJan(ActivityData obj, int index) {
        Boolean jan = Boolean.TRUE;
        obj.setJan(jan);
    }
    
    public void ParticipationDataOnDemand.setExtraSchoolFeb(ActivityData obj, int index) {
        Boolean feb = Boolean.TRUE;
        obj.setFeb(feb);
    }
    
    public void ParticipationDataOnDemand.setExtraSchoolMar(ActivityData obj, int index) {
        Boolean mar = Boolean.TRUE;
        obj.setMar(mar);
    }
    
    public void ParticipationDataOnDemand.setExtraSchoolApr(ActivityData obj, int index) {
        Boolean apr = Boolean.TRUE;
        obj.setApr(apr);
    }
    
    public void ParticipationDataOnDemand.setExtraSchoolMay(ActivityData obj, int index) {
        Boolean may = Boolean.TRUE;
        obj.setMay(may);
    }
    
    public void ParticipationDataOnDemand.setExtraSchoolJun(ActivityData obj, int index) {
        Boolean jun = Boolean.TRUE;
        obj.setJun(jun);
    }
    
    public void ParticipationDataOnDemand.setExtraSchoolJul(ActivityData obj, int index) {
        Boolean jul = Boolean.TRUE;
        obj.setJul(jul);
    }
    
    public void ParticipationDataOnDemand.setExtraSchoolAug(ActivityData obj, int index) {
        Boolean aug = Boolean.TRUE;
        obj.setAug(aug);
    }
    
    public void ParticipationDataOnDemand.setExtraSchoolSep(ActivityData obj, int index) {
        Boolean sep = Boolean.TRUE;
        obj.setSep(sep);
    }
    
    public void ParticipationDataOnDemand.setExtraSchoolOct(ActivityData obj, int index) {
        Boolean oct = Boolean.TRUE;
        obj.setOct(oct);
    }
    
    public void ParticipationDataOnDemand.setExtraSchoolNov(ActivityData obj, int index) {
        Boolean nov = Boolean.TRUE;
        obj.setNov(nov);
    }
    
    public void ParticipationDataOnDemand.setExtraSchoolDec(ActivityData obj, int index) {
        Boolean dec = Boolean.TRUE;
        obj.setDec(dec);
    }
    
    public void ParticipationDataOnDemand.setGroupCounseling(Participation obj, int index) {
        ActivityData embeddedClass = new ActivityData();
        setGroupCounselingJan(embeddedClass, index);
        setGroupCounselingFeb(embeddedClass, index);
        setGroupCounselingMar(embeddedClass, index);
        setGroupCounselingApr(embeddedClass, index);
        setGroupCounselingMay(embeddedClass, index);
        setGroupCounselingJun(embeddedClass, index);
        setGroupCounselingJul(embeddedClass, index);
        setGroupCounselingAug(embeddedClass, index);
        setGroupCounselingSep(embeddedClass, index);
        setGroupCounselingOct(embeddedClass, index);
        setGroupCounselingNov(embeddedClass, index);
        setGroupCounselingDec(embeddedClass, index);
        obj.setGroupCounseling(embeddedClass);
    }
    
    public void ParticipationDataOnDemand.setGroupCounselingJan(ActivityData obj, int index) {
        Boolean jan = Boolean.TRUE;
        obj.setJan(jan);
    }
    
    public void ParticipationDataOnDemand.setGroupCounselingFeb(ActivityData obj, int index) {
        Boolean feb = Boolean.TRUE;
        obj.setFeb(feb);
    }
    
    public void ParticipationDataOnDemand.setGroupCounselingMar(ActivityData obj, int index) {
        Boolean mar = Boolean.TRUE;
        obj.setMar(mar);
    }
    
    public void ParticipationDataOnDemand.setGroupCounselingApr(ActivityData obj, int index) {
        Boolean apr = Boolean.TRUE;
        obj.setApr(apr);
    }
    
    public void ParticipationDataOnDemand.setGroupCounselingMay(ActivityData obj, int index) {
        Boolean may = Boolean.TRUE;
        obj.setMay(may);
    }
    
    public void ParticipationDataOnDemand.setGroupCounselingJun(ActivityData obj, int index) {
        Boolean jun = Boolean.TRUE;
        obj.setJun(jun);
    }
    
    public void ParticipationDataOnDemand.setGroupCounselingJul(ActivityData obj, int index) {
        Boolean jul = Boolean.TRUE;
        obj.setJul(jul);
    }
    
    public void ParticipationDataOnDemand.setGroupCounselingAug(ActivityData obj, int index) {
        Boolean aug = Boolean.TRUE;
        obj.setAug(aug);
    }
    
    public void ParticipationDataOnDemand.setGroupCounselingSep(ActivityData obj, int index) {
        Boolean sep = Boolean.TRUE;
        obj.setSep(sep);
    }
    
    public void ParticipationDataOnDemand.setGroupCounselingOct(ActivityData obj, int index) {
        Boolean oct = Boolean.TRUE;
        obj.setOct(oct);
    }
    
    public void ParticipationDataOnDemand.setGroupCounselingNov(ActivityData obj, int index) {
        Boolean nov = Boolean.TRUE;
        obj.setNov(nov);
    }
    
    public void ParticipationDataOnDemand.setGroupCounselingDec(ActivityData obj, int index) {
        Boolean dec = Boolean.TRUE;
        obj.setDec(dec);
    }
    
    public void ParticipationDataOnDemand.setIndividualCounseling(Participation obj, int index) {
        ActivityData embeddedClass = new ActivityData();
        setIndividualCounselingJan(embeddedClass, index);
        setIndividualCounselingFeb(embeddedClass, index);
        setIndividualCounselingMar(embeddedClass, index);
        setIndividualCounselingApr(embeddedClass, index);
        setIndividualCounselingMay(embeddedClass, index);
        setIndividualCounselingJun(embeddedClass, index);
        setIndividualCounselingJul(embeddedClass, index);
        setIndividualCounselingAug(embeddedClass, index);
        setIndividualCounselingSep(embeddedClass, index);
        setIndividualCounselingOct(embeddedClass, index);
        setIndividualCounselingNov(embeddedClass, index);
        setIndividualCounselingDec(embeddedClass, index);
        obj.setIndividualCounseling(embeddedClass);
    }
    
    public void ParticipationDataOnDemand.setIndividualCounselingJan(ActivityData obj, int index) {
        Boolean jan = Boolean.TRUE;
        obj.setJan(jan);
    }
    
    public void ParticipationDataOnDemand.setIndividualCounselingFeb(ActivityData obj, int index) {
        Boolean feb = Boolean.TRUE;
        obj.setFeb(feb);
    }
    
    public void ParticipationDataOnDemand.setIndividualCounselingMar(ActivityData obj, int index) {
        Boolean mar = Boolean.TRUE;
        obj.setMar(mar);
    }
    
    public void ParticipationDataOnDemand.setIndividualCounselingApr(ActivityData obj, int index) {
        Boolean apr = Boolean.TRUE;
        obj.setApr(apr);
    }
    
    public void ParticipationDataOnDemand.setIndividualCounselingMay(ActivityData obj, int index) {
        Boolean may = Boolean.TRUE;
        obj.setMay(may);
    }
    
    public void ParticipationDataOnDemand.setIndividualCounselingJun(ActivityData obj, int index) {
        Boolean jun = Boolean.TRUE;
        obj.setJun(jun);
    }
    
    public void ParticipationDataOnDemand.setIndividualCounselingJul(ActivityData obj, int index) {
        Boolean jul = Boolean.TRUE;
        obj.setJul(jul);
    }
    
    public void ParticipationDataOnDemand.setIndividualCounselingAug(ActivityData obj, int index) {
        Boolean aug = Boolean.TRUE;
        obj.setAug(aug);
    }
    
    public void ParticipationDataOnDemand.setIndividualCounselingSep(ActivityData obj, int index) {
        Boolean sep = Boolean.TRUE;
        obj.setSep(sep);
    }
    
    public void ParticipationDataOnDemand.setIndividualCounselingOct(ActivityData obj, int index) {
        Boolean oct = Boolean.TRUE;
        obj.setOct(oct);
    }
    
    public void ParticipationDataOnDemand.setIndividualCounselingNov(ActivityData obj, int index) {
        Boolean nov = Boolean.TRUE;
        obj.setNov(nov);
    }
    
    public void ParticipationDataOnDemand.setIndividualCounselingDec(ActivityData obj, int index) {
        Boolean dec = Boolean.TRUE;
        obj.setDec(dec);
    }
    
    public void ParticipationDataOnDemand.setParentalCommunication(Participation obj, int index) {
        ActivityData embeddedClass = new ActivityData();
        setParentalCommunicationJan(embeddedClass, index);
        setParentalCommunicationFeb(embeddedClass, index);
        setParentalCommunicationMar(embeddedClass, index);
        setParentalCommunicationApr(embeddedClass, index);
        setParentalCommunicationMay(embeddedClass, index);
        setParentalCommunicationJun(embeddedClass, index);
        setParentalCommunicationJul(embeddedClass, index);
        setParentalCommunicationAug(embeddedClass, index);
        setParentalCommunicationSep(embeddedClass, index);
        setParentalCommunicationOct(embeddedClass, index);
        setParentalCommunicationNov(embeddedClass, index);
        setParentalCommunicationDec(embeddedClass, index);
        obj.setParentalCommunication(embeddedClass);
    }
    
    public void ParticipationDataOnDemand.setParentalCommunicationJan(ActivityData obj, int index) {
        Boolean jan = Boolean.TRUE;
        obj.setJan(jan);
    }
    
    public void ParticipationDataOnDemand.setParentalCommunicationFeb(ActivityData obj, int index) {
        Boolean feb = Boolean.TRUE;
        obj.setFeb(feb);
    }
    
    public void ParticipationDataOnDemand.setParentalCommunicationMar(ActivityData obj, int index) {
        Boolean mar = Boolean.TRUE;
        obj.setMar(mar);
    }
    
    public void ParticipationDataOnDemand.setParentalCommunicationApr(ActivityData obj, int index) {
        Boolean apr = Boolean.TRUE;
        obj.setApr(apr);
    }
    
    public void ParticipationDataOnDemand.setParentalCommunicationMay(ActivityData obj, int index) {
        Boolean may = Boolean.TRUE;
        obj.setMay(may);
    }
    
    public void ParticipationDataOnDemand.setParentalCommunicationJun(ActivityData obj, int index) {
        Boolean jun = Boolean.TRUE;
        obj.setJun(jun);
    }
    
    public void ParticipationDataOnDemand.setParentalCommunicationJul(ActivityData obj, int index) {
        Boolean jul = Boolean.TRUE;
        obj.setJul(jul);
    }
    
    public void ParticipationDataOnDemand.setParentalCommunicationAug(ActivityData obj, int index) {
        Boolean aug = Boolean.TRUE;
        obj.setAug(aug);
    }
    
    public void ParticipationDataOnDemand.setParentalCommunicationSep(ActivityData obj, int index) {
        Boolean sep = Boolean.TRUE;
        obj.setSep(sep);
    }
    
    public void ParticipationDataOnDemand.setParentalCommunicationOct(ActivityData obj, int index) {
        Boolean oct = Boolean.TRUE;
        obj.setOct(oct);
    }
    
    public void ParticipationDataOnDemand.setParentalCommunicationNov(ActivityData obj, int index) {
        Boolean nov = Boolean.TRUE;
        obj.setNov(nov);
    }
    
    public void ParticipationDataOnDemand.setParentalCommunicationDec(ActivityData obj, int index) {
        Boolean dec = Boolean.TRUE;
        obj.setDec(dec);
    }
    
    public void ParticipationDataOnDemand.setLocalMeetings(Participation obj, int index) {
        ActivityData embeddedClass = new ActivityData();
        setLocalMeetingsJan(embeddedClass, index);
        setLocalMeetingsFeb(embeddedClass, index);
        setLocalMeetingsMar(embeddedClass, index);
        setLocalMeetingsApr(embeddedClass, index);
        setLocalMeetingsMay(embeddedClass, index);
        setLocalMeetingsJun(embeddedClass, index);
        setLocalMeetingsJul(embeddedClass, index);
        setLocalMeetingsAug(embeddedClass, index);
        setLocalMeetingsSep(embeddedClass, index);
        setLocalMeetingsOct(embeddedClass, index);
        setLocalMeetingsNov(embeddedClass, index);
        setLocalMeetingsDec(embeddedClass, index);
        obj.setLocalMeetings(embeddedClass);
    }
    
    public void ParticipationDataOnDemand.setLocalMeetingsJan(ActivityData obj, int index) {
        Boolean jan = Boolean.TRUE;
        obj.setJan(jan);
    }
    
    public void ParticipationDataOnDemand.setLocalMeetingsFeb(ActivityData obj, int index) {
        Boolean feb = Boolean.TRUE;
        obj.setFeb(feb);
    }
    
    public void ParticipationDataOnDemand.setLocalMeetingsMar(ActivityData obj, int index) {
        Boolean mar = Boolean.TRUE;
        obj.setMar(mar);
    }
    
    public void ParticipationDataOnDemand.setLocalMeetingsApr(ActivityData obj, int index) {
        Boolean apr = Boolean.TRUE;
        obj.setApr(apr);
    }
    
    public void ParticipationDataOnDemand.setLocalMeetingsMay(ActivityData obj, int index) {
        Boolean may = Boolean.TRUE;
        obj.setMay(may);
    }
    
    public void ParticipationDataOnDemand.setLocalMeetingsJun(ActivityData obj, int index) {
        Boolean jun = Boolean.TRUE;
        obj.setJun(jun);
    }
    
    public void ParticipationDataOnDemand.setLocalMeetingsJul(ActivityData obj, int index) {
        Boolean jul = Boolean.TRUE;
        obj.setJul(jul);
    }
    
    public void ParticipationDataOnDemand.setLocalMeetingsAug(ActivityData obj, int index) {
        Boolean aug = Boolean.TRUE;
        obj.setAug(aug);
    }
    
    public void ParticipationDataOnDemand.setLocalMeetingsSep(ActivityData obj, int index) {
        Boolean sep = Boolean.TRUE;
        obj.setSep(sep);
    }
    
    public void ParticipationDataOnDemand.setLocalMeetingsOct(ActivityData obj, int index) {
        Boolean oct = Boolean.TRUE;
        obj.setOct(oct);
    }
    
    public void ParticipationDataOnDemand.setLocalMeetingsNov(ActivityData obj, int index) {
        Boolean nov = Boolean.TRUE;
        obj.setNov(nov);
    }
    
    public void ParticipationDataOnDemand.setLocalMeetingsDec(ActivityData obj, int index) {
        Boolean dec = Boolean.TRUE;
        obj.setDec(dec);
    }
    
    public void ParticipationDataOnDemand.setParentalCommunicationDetailed(Participation obj, int index) {
        ParentalCommunicationData embeddedClass = new ParentalCommunicationData();
        setParentalCommunicationDetailedJan(embeddedClass, index);
        setParentalCommunicationDetailedFeb(embeddedClass, index);
        setParentalCommunicationDetailedMar(embeddedClass, index);
        setParentalCommunicationDetailedApr(embeddedClass, index);
        setParentalCommunicationDetailedMay(embeddedClass, index);
        setParentalCommunicationDetailedJun(embeddedClass, index);
        setParentalCommunicationDetailedJul(embeddedClass, index);
        setParentalCommunicationDetailedAug(embeddedClass, index);
        setParentalCommunicationDetailedSep(embeddedClass, index);
        setParentalCommunicationDetailedOct(embeddedClass, index);
        setParentalCommunicationDetailedNov(embeddedClass, index);
        setParentalCommunicationDetailedDec(embeddedClass, index);
        obj.setParentalCommunicationDetailed(embeddedClass);
    }
    
    public void ParticipationDataOnDemand.setParentalCommunicationDetailedJan(ParentalCommunicationData obj, int index) {
        ParentState jan = ParentState.class.getEnumConstants()[0];
        obj.setJan(jan);
    }
    
    public void ParticipationDataOnDemand.setParentalCommunicationDetailedFeb(ParentalCommunicationData obj, int index) {
        ParentState feb = ParentState.class.getEnumConstants()[0];
        obj.setFeb(feb);
    }
    
    public void ParticipationDataOnDemand.setParentalCommunicationDetailedMar(ParentalCommunicationData obj, int index) {
        ParentState mar = ParentState.class.getEnumConstants()[0];
        obj.setMar(mar);
    }
    
    public void ParticipationDataOnDemand.setParentalCommunicationDetailedApr(ParentalCommunicationData obj, int index) {
        ParentState apr = ParentState.class.getEnumConstants()[0];
        obj.setApr(apr);
    }
    
    public void ParticipationDataOnDemand.setParentalCommunicationDetailedMay(ParentalCommunicationData obj, int index) {
        ParentState may = ParentState.class.getEnumConstants()[0];
        obj.setMay(may);
    }
    
    public void ParticipationDataOnDemand.setParentalCommunicationDetailedJun(ParentalCommunicationData obj, int index) {
        ParentState jun = ParentState.class.getEnumConstants()[0];
        obj.setJun(jun);
    }
    
    public void ParticipationDataOnDemand.setParentalCommunicationDetailedJul(ParentalCommunicationData obj, int index) {
        ParentState jul = ParentState.class.getEnumConstants()[0];
        obj.setJul(jul);
    }
    
    public void ParticipationDataOnDemand.setParentalCommunicationDetailedAug(ParentalCommunicationData obj, int index) {
        ParentState aug = ParentState.class.getEnumConstants()[0];
        obj.setAug(aug);
    }
    
    public void ParticipationDataOnDemand.setParentalCommunicationDetailedSep(ParentalCommunicationData obj, int index) {
        ParentState sep = ParentState.class.getEnumConstants()[0];
        obj.setSep(sep);
    }
    
    public void ParticipationDataOnDemand.setParentalCommunicationDetailedOct(ParentalCommunicationData obj, int index) {
        ParentState oct = ParentState.class.getEnumConstants()[0];
        obj.setOct(oct);
    }
    
    public void ParticipationDataOnDemand.setParentalCommunicationDetailedNov(ParentalCommunicationData obj, int index) {
        ParentState nov = ParentState.class.getEnumConstants()[0];
        obj.setNov(nov);
    }
    
    public void ParticipationDataOnDemand.setParentalCommunicationDetailedDec(ParentalCommunicationData obj, int index) {
        ParentState dec = ParentState.class.getEnumConstants()[0];
        obj.setDec(dec);
    }
    
    public void ParticipationDataOnDemand.setPupilId(Participation obj, int index) {
        Long pupilId = new Integer(index).longValue();
        obj.setPupilId(pupilId);
    }
    
    public void ParticipationDataOnDemand.setYear(Participation obj, int index) {
        int year = index;
        obj.setYear(year);
    }
    
    public Participation ParticipationDataOnDemand.getSpecificParticipation(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        Participation obj = data.get(index);
        Long id = obj.getId();
        return Participation.findParticipation(id);
    }
    
    public Participation ParticipationDataOnDemand.getRandomParticipation() {
        init();
        Participation obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return Participation.findParticipation(id);
    }
    
    public boolean ParticipationDataOnDemand.modifyParticipation(Participation obj) {
        return false;
    }
    
    public void ParticipationDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = Participation.findParticipationEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'Participation' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<Participation>();
        for (int i = 0; i < 10; i++) {
            Participation obj = getNewTransientParticipation(i);
            try {
                obj.persist();
            } catch (final ConstraintViolationException e) {
                final StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    final ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
                }
                throw new IllegalStateException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
